version: "3.2"
services:
  harbor:
    build: .
    command: "mix phx.server"
    ports: 
      - 4000:4000
    networks:
      - harbor
      - db
    volumes:
      - type: bind
        source: ./
        target: /usr/harbor
    depends_on:
      - db
  
  db:
    image: postgres
    restart: always
    networks:
      - db
    environment:
      POSTGRES_PASSWORD: harbor #TODO

networks:
  harbor:
  db: