version: "3.6"
services:
  harbor-api:
    build: .
    command: "mix phx.server"
    ports: 
      - 4000:4000
    networks:
      - db
      - harbor
    depends_on:
      - db
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - type: bind
        source: ./
        target: /usr/harbor

  harbor-web:
    image: "node:8"
    working_dir: /usr/web
    command: "npm run dev"
    ports:
      - 8080:8080
    depends_on:
      - harbor-api
    volumes:
      - type: bind
        source: ./web
        target: /usr/web
      - node_modules:/usr/web/node_modules

  db:
    image: postgres
    restart: always
    networks:
      - db
    ports:
      - 5432
    environment:
      POSTGRES_PASSWORD: harbor #TODO

networks:
  harbor:
  db:

volumes:
  node_modules: